-- Plugins will be downloaded under the specified directory.

require("blaine.core")
require("blaine.lazy")

--vim.opt.clipboard = "unnamedplus"
--vim.opt.number = true
--vim.opt.autoindent = true
--vim.opt.tabstop = 4
--vim.opt.shiftwidth = 4
--vim.opt.smarttab = true
--vim.opt.softtabstop = 3
--vim.opt.mouse = "a"
--vim.opt.modifiable = true
--
--
---- Plugins
--local Plug = vim.fn["plug#"]
--vim.call("plug#begin")
--Plug("https://github.com/vim-airline/vim-airline.git")
--Plug("https://github.com/preservim/nerdtree.git")
--Plug("https://github.com/junegunn/vim-github-dashboard.git")
--Plug("https://github.com/preservim/tagbar.git")
--Plug("https://github.com/ap/vim-css-color")
--Plug("https://github.com/rafi/awesome-vim-colorschemes")
--Plug("neoclide/coc.nvim", {["branch"] = "release"})
--Plug("https://github.com/ryanoasis/vim-devicons")
--Plug("https://github.com/tc50cal/vim-terminal")
--Plug("https://github.com/terryma/vim-multiple-cursors")
--Plug("https://github.com/nvim-lua/plenary.nvim.git")
--Plug("https://github.com/nvim-telescope/telescope.nvim.git")
--Plug("https://github.com/BurntSushi/ripgrep.git")
--Plug("https://github.com/lewis6991/gitsigns.nvim.git")
--Plug("https://github.com/stevearc/conform.nvim.git")
--Plug("https://github.com/williamboman/mason.nvim.git")
--Plug("https://github.com/kdheepak/lazygit.nvim.git")
--vim.call('plug#end')
--
--
--require("mason").setup()
--require('gitsigns').setup() 
--require('conform').setup({
--			formatters_by_ft = {
--		lua = {"stylelua"},    go = { "goimports", "gofmt" },
--    -- Use a sub-list to run only the first available formatter
--    javascript = { { "prettierd", "prettier" } },
--
--	}
--
--})
--
---- Call this if neoclide/coc.nvim needs something
---- vim.call('coc#util#install')
--
--
---- Key mappings
--vim.api.nvim_set_keymap('n', '<C-f>', ':NERDTreeFocus<CR>', {noremap = true})
--vim.api.nvim_set_keymap('n', '<C-n>', ':NERDTree<CR>', {noremap = true})
--vim.api.nvim_set_keymap('n', '<C-t>', ':NERDTreeToggle<CR>', {noremap = true})
--vim.api.nvim_set_keymap('n', '<C-l>', ':call CocActionAsync("jumpDefinition")<CR>', {noremap = true})
--vim.api.nvim_set_keymap('n', 'ff', ':Telescope find_files default_text=', {noremap = true})
--vim.api.nvim_set_keymap('n', 'lg', ':Telescope live_grep default_text=', {noremap = true})
--vim.api.nvim_set_keymap('n', 'gs', ':Telescope grep_string default_text=', {noremap = true})
--vim.api.nvim_set_keymap('n', 'gf', ':Telescope git_files default_text=', {noremap = true})
--vim.api.nvim_set_keymap('n', '<F8>', ':TagbarToggle<CR>', {noremap = true})
--vim.api.nvim_set_keymap('n', '<F9>', ':LazyGit<Return>', {noremap = true})
--
--vim.api.nvim_create_autocmd("BufWritePre", {
--  pattern = "*",
--  callback = function(args)
--    require("conform").format({ bufnr = args.buf })
--  end,
--})
--
---- Use `[g` and `]g` to navigate diagnostics
---- Use `:CocDiagnostics` to get all diagnostics of current buffer in location list.
--vim.api.nvim_set_keymap('n', '[g', '<Plug>(coc-diagnostic-prev)', {silent = true})
--vim.api.nvim_set_keymap('n', ']g', '<Plug>(coc-diagnostic-next)', {silent = true})
--
---- Configuration for NERDTree
--vim.g.NERDTreeDirArrowExpandable = "+"
--vim.g.NERDTreeDirArrowCollapsible = "~"
--
---- Airline configuration
--vim.g.airline_powerline_fonts = 1
--
---- Key mapping for exiting insert mode quickly
--vim.api.nvim_set_keymap('i', 'jk', '<ESC>', {})
--
